from typing import Union, Tuple, List

import discord


class CalculateMods:
    def __init__(self, mods: Union[list, str] = ...): ...

    def ar(self, raw_ar: Union[float, int] = ...) -> Tuple[float, float, list]: ...

    def cs(self, raw_cs: Union[float, int] = ...) -> Tuple[float, list]: ...

    def od(self, raw_od: Union[float, int] = ...) -> Tuple[float, float, list]: ...

    def hp(self, raw_hp: Union[float, int] = ...) -> Tuple[float, list]: ...


def parse_mods_string(mods: str = ...) -> List[str]: ...


def parse_mods_int(mods: int = ...) -> List[str]: ...


def sanitize_mods(mods: Union[list, set] = ...) -> Union[list, set]: ...


def mod_int(mod_list: Union[list, set, int] = ...) -> int: ...


def get_map_link(link: str = ..., **kwargs) -> Tuple[Union[int, str], str]: ...


def calculate_acc(n300: int = ..., n100: int = ..., n50: int = ..., nMiss: int = ...) -> float: ...


def speed_multiplier(mods: Union[list, set] = ...) -> float: ...


def get_rank_emoji(rank: str = ..., client: discord.Client = ...) -> Union[bool, discord.Emoji, str]: ...


def download_mapset(link_id: Union[str, int] = ..., link: str = ...) -> str: ...
